ARG BASEIMAGE_TAG='latest'
FROM sphinxdoc/sphinx-latexpdf:${BASEIMAGE_TAG}

COPY requirements.txt /requirements.txt
RUN set -x && \
  pip3 install -U -r /requirements.txt && \
  rm -v /requirements.txt

WORKDIR /docs
